# Flow Matching RD图 Sim2Real 配置文件

# ========== 数据配置 ==========
data:
  data_root: "./data"                # 数据根目录
  val_data_root: null                # 验证集路径（null表示使用训练集）
  max_speed: 30.0                    # RD图最大速度范围 ±30 m/s
  max_range: 200.0                   # RD图最大距离 0-200 m

# ========== 热力图配置 ==========
heatmap:
  sigma: 10.0                        # 高斯热力图标准差

# ========== Loss配置 ==========
loss:
  weight_factor: 50                  # 目标区域权重因子（30-100）
  threshold: 0.1                     # 热力图二值化阈值
  pool_size: 8                       # Max Pooling核大小

# ========== 训练配置 ==========
train:
  batch_size: 4                      # 批大小
  num_epochs: 100                    # 训练轮数
  learning_rate: 0.0001              # 学习率
  num_workers: 4                     # 数据加载进程数
  gradient_accumulation_steps: 1     # 梯度累积步数（实际batch=batch_size*steps）
  
  # 学习率调度
  lr_warmup_epochs: 5                # 预热轮数
  
  # Flow Matching
  noise_scale: 0.01                  # 训练时噪声尺度
  
  # 设备
  device: "cuda"                     # cuda 或 cpu
  mixed_precision: true              # 混合精度训练
  
  # 保存和日志
  save_interval: 5                   # 每N个epoch保存检查点
  log_interval: 50                   # 每N个iteration打印日志
  save_best_only: false              # 是否只保存最佳模型
  keep_last_n_checkpoints: 5         # 保留最近N个检查点（0=全部保留）
  
  # 早停机制
  early_stopping:
    enabled: true                    # 是否启用早停
    patience: 20                     # 容忍N个epoch无改善
    min_delta: 0.0001                # 最小改善阈值
    monitor: "loss"                  # 监控指标

# ========== 推理配置 ==========
inference:
  ode_steps: 20                      # ODE求解步数
  ode_method: "euler"                # ODE求解方法：euler 或 rk4

# ========== 路径配置 ==========
paths:
  output_dir: "./outputs"            # 输出目录
  log_dir: "./logs"                  # TensorBoard日志目录
  checkpoint_dir: "./checkpoints"    # 检查点保存目录

# ========== 恢复训练 ==========
resume:
  checkpoint: null                   # 恢复训练的检查点路径（null=从头开始）

